### ISSUE TITLE
The application won't start

### ISSUE THREAD

**Issue by chillrage** [Androidacy/MagiskModuleManager#28]
**Describe the bug**
The application doesn't start properly and shows an error message whenever i open it. I first encountered the bug when I updated the app to version 2.0.1

**To Reproduce**
Open the app.

**Expected behavior**
The app opens and works as intended.

**Screenshots**
![Screenshot_20230611-100444_Fox's Magisk Module Manager](https://github.com/Androidacy/MagiskModuleManager/assets/110960776/00de6dc7-adc3-4863-bd64-ee2478402403)

**Device info(please complete the following information):**
 - OS: [ROM and version, ie Havoc-OS 4.12]
 - App Version [e.g. 22]

**Additional context**

**Comment by tobby88** [comment]
Uninstalled and reinstalled the app. Problem is still there.

**Comment by MrHappy** [comment]
I have the same issue. Same version. Running on LOS20.

**Comment by Simon1511** [comment]
Same issue here. Neither clearing data of the app nor reinstalling helps.

**Comment by ghostrevenge** [comment]
Hi same problem is happening to me , 
Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.MainActivity}: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3642)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3779)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7926)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at com.fox2code.mmm.MainActivity.onCreate(SourceFile:791)
	at android.app.Activity.performCreate(Activity.java:8383)
	at android.app.Activity.performCreate(Activity.java:8362)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1424)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
	... 12 more

**Comment by ghostrevenge** [comment]
I have reinstalled latest version already

**Comment by chillrage** [comment]
> Clean installing version 2.1.1 will fix your issue most likely, but this is a known edge case with old builds that we've already addressed.

I've tried clean installing, trying old builds etc
the problem still persists

**Comment by MrHappy** [comment]
Version 2.0.1 from the original creator works fine. [Here](https://github.com/Fox2Code/FoxMagiskModuleManager/releases)
Probably because it does not check for version at startup...

**Comment by Yaff1e** [comment]
Same problem on LOS20 on a OnePlus 6T

**Comment by Eridyne** [comment]
Same issue, same stacktrace. Seems Androidacy is much too eager to close issues.

**Comment by gustavokch** [comment]
Same issue here on LOS20.

**Comment by MrHappy** [comment]
If I recall correctly I once used an app which also checked if there was a newer version available (and an internet connection) and if there was (or no internet) it would fail to start...
