### ISSUE TITLE
[BUG] This build has expired. Please download a stable build or update to the latest version.

### ISSUE THREAD

**Issue by PA733** [Androidacy/MagiskModuleManager#29]
**Describe the bug**
After a clean install, The app keeps crashing.

**To Reproduce**
1. Open FoxMMM
2. See error.

**Expected behavior**
App will work.

**Screenshots**
![Screenshot_20230611-185139_Fox 的 Magisk 模块管理器](https://github.com/Androidacy/MagiskModuleManager/assets/67588574/1fe98942-1685-4354-b29a-0322ae541ea4)

**Device info(please complete the following information):**
 - Device: Pixel 3a XL (bonito)
 - OS: Pixel Experience 13
 - App Version 2.1.0

**Logs**
```
堆栈跟踪: 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.MainActivity}: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3642)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3779)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7925)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at com.fox2code.mmm.MainActivity.onCreate(SourceFile:791)
	at android.app.Activity.performCreate(Activity.java:8347)
	at android.app.Activity.performCreate(Activity.java:8326)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
	... 12 more
```

**Comment by Lalarian** [comment]
Same on my two phones. One of which I just finished setting up 10 hours, ago.
One is running Resurreciton Remix on Android 10 base and thje other phone is running crdroid on Android 13 base.

**Comment by Kay-Kostrowski** [comment]
Allways good not to be the only one!
First I thought I have messed up some by debloating and tweaking today... 😇
Same problem here since couple hours. Re-installation out of panic did not help and now it is not even listet in Magisk superuser list nor asking for root permission. And I lost the possibility to send integrated error report via app.

🦊3m version 2.1.1 - Galaxy Note20 ultra exynos and what's left of Android13 (N986BXXS5GWA7), 

![20230611_165705.png](https://github.com/Androidacy/MagiskModuleManager/assets/84748960/7f8c2308-db5f-4057-82f0-b96cec91503a)

**Comment by dimon222** [comment]
@androidacy-user please reopen this. This is not fixed and no, clean reinstall doesn't help.
The problem is global, I tried earlier releases as well and it behaves same way everywhere. The app version didn't change since last time, so it clearly expired. I tried with .apk binaries on github in 2.1.1 release.

**Comment by much-doge** [comment]
@androidacy-user even after downloading the latest build on the website (the signed version), the error still appear with the exact error, now this is just silly

`Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.MainActivity}: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:237)
 at android.app.ActivityThread.main(ActivityThread.java:8167)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
 at com.fox2code.mmm.MainActivity.onCreate(SourceFile:791)
 at android.app.Activity.performCreate(Activity.java:7963)
 at android.app.Activity.performCreate(Activity.java:7952)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
 ... 11 more`

**Comment by PA733** [comment]
> Intended behavior. Debug builds expire after a few days as they're not intended to be used as a daily driver.
> 
> Please install the latest stable, release build.

I repeat, I did not use the debug build.
The same problem occurs using the previous release version.

**Comment by PA733** [comment]
Fixed in #31.
This issue should be reopened and closed.
