### ISSUE TITLE
[BUG] REPLACE_ME

### ISSUE THREAD

**Issue by WestSemih123** [Androidacy/MagiskModuleManager#30]
Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.MainActivity}: io.realm.exceptions.RealmFileException: Failed to open Realm file at path '/data/user/0/com.fox2code.mmm/realms/ReposList.realm': Realm file decryption failed (Decryption failed: 'unable to decrypt after 0 seconds (retry_count=4
      from=i != bytes_read
      size=4096)') (/data/user/0/com.fox2code.mmm/realms/ReposList.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: ACCESS_ERROR.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3432)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3596)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:200)
	at android.os.Looper.loop(Looper.java:286)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: io.realm.exceptions.RealmFileException: Failed to open Realm file at path '/data/user/0/com.fox2code.mmm/realms/ReposList.realm': Realm file decryption failed (Decryption failed: 'unable to decrypt after 0 seconds (retry_count=4
      from=i != bytes_read
      size=4096)') (/data/user/0/com.fox2code.mmm/realms/ReposList.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: ACCESS_ERROR.
	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
	at io.realm.internal.OsSharedRealm.<init>(SourceFile:11)
	at io.realm.internal.OsSharedRealm.getInstance(SourceFile:6)
	at hg.<init>(SourceFile:18)
	at lf1.<init>(SourceFile:8)
	at vf1.b(SourceFile:96)
	at lf1.l0(SourceFile:5)
	at com.fox2code.mmm.MainActivity.onCreate(SourceFile:77)
	at android.app.Activity.performCreate(Activity.java:7994)
	at android.app.Activity.performCreate(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1321)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3405)
	... 12 more

**Comment by Releece** [comment]
I had the exact same crash report.
I received an Android notification that a new version of MMM is available, clicked on it and it went straight to the bugreport screen with the same crash log.
Pressing (Submit &) Restart immediately leads to the same kog again.
I then decided to just delete this reposList.Realm file that the log says can't be decrypted. The app still crashes but now with a very different log:
`Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.MainActivity}: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3642)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3779)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7926)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at com.fox2code.mmm.MainActivity.onCreate(SourceFile:791)
	at android.app.Activity.performCreate(Activity.java:8365)
	at android.app.Activity.performCreate(Activity.java:8344)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1424)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
	... 12 more
`
I have checked and enabled all possible permissions & appops and such that were disabled using App Manager, unfortunately this still gives the  same Realm ACCES_ERROR.

I must report that before today the app was basically unusable as it was already constantly crashing e.g. whenever I would install a module locally or by downloading, whenever I pressed on the installed tab it would take 20 secs to fetch the repo's and then immediately crash + other random crashes.

Since today however it doesn't even start as it goes straight to the bug reporting window, so something must have changed.


Before the app migrated to the Androidacy GitHub and got updated I never had any issue with FoxMMM on my device:
Android 13, EvolutionX ROM on a OnePlus Nord 2 5g (codename denniz).

Good luck integrating your code into this Fork, it seems it's not too easy of a job

**Comment by Bodenseematze** [comment]
> Fixed build has been re-uploaded [here](https://www.androidacy.com/downloads/?view=FoxMMM). An error in our linting tool caused a conditional check to be made unconditional. We apologize for the error. **The re-uploaded 2.1.1 build has nothing else changed.**

I have the same problem (see #34) - I now reinstalled the re-uploaded version and initially the StackTrace still came.
Then I "reset the app" - and that helps - the initial startup screen appears and I was able to re-do the initial setup.

Thumbs up!
