### ISSUE TITLE
[BUG] This build has expired. Please download a stable build or update to the latest version.

### ISSUE THREAD

**Issue by V3semir** [Androidacy/MagiskModuleManager#33]
**Describe the bug**
```java
Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.MainActivity}: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3642)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3779)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7925)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at com.fox2code.mmm.MainActivity.onCreate(SourceFile:791)
	at android.app.Activity.performCreate(Activity.java:8347)
	at android.app.Activity.performCreate(Activity.java:8326)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
	... 12 more
``` 

**To Reproduce**
1. Open the app.

**Expected behavior**
Being able to use the app.

**Screenshots**
![Screenshot_20230612-071127_Fox's Magisk Module Manager](https://github.com/Androidacy/MagiskModuleManager/assets/45462483/f603e91f-bd4f-4e52-a07f-e273ffaa540f)

**Device info:**
 - Device: Samsung Galaxy S10+
 - OS: Pixel Experience Plus (TQ2A.230505.002 PixelExperience_Plus_beyond2lte-13.0-20230504-0926-OFFICIAL)
 - App Version: 2.1.1

**Comment by V3semir** [comment]
> App data has been corrupted Please reset the app and try again.

That's not it. I tried multiple times, even completely reinstalled the app. I even tried on a different phone.

**Comment by Chloe-ko** [comment]
Hi, I'm having the exact same issue. This issue just magically appeared a short while ago, I didn't change anything. I also tried resetting or reinstalling the app, no change.

**Comment by LeeBinder** [comment]
Same here. Resetting the app by removing all data & cache does _NOT_ help.

Oh well, sh*t happens - we're all just human beans .. ;)

**Comment by elhennig** [comment]
Same here on a Fairphone 4 with latest FPOS release

**Comment by Daviteusz** [comment]
It's fixed, but Androidacy forgot to properly inform users.
https://github.com/Androidacy/MagiskModuleManager/issues/30#issuecomment-1586411758

When apk is fixed, new release should be made or files in actual release should be replaced with fixed version.

Also new issue should be created (and pinned) to inform users why 2.1.1 version is not working and how to fix that.

**Comment by LeeBinder** [comment]
@Daviteusz I 100% agree !!!!!!

**Comment by MrHappy** [comment]
Why would you let the app stop working when there is a new version? It is not said it won't work...
Does it also crap out if there is no internet available?

**Comment by LeeBinder** [comment]
hm well - Telegram is Telegram and GitHub is GitHub. Please try also look at it from a user perspective.

Anyway, thanks for fixing this. Whoever wants to can run the latest compiled artifact. The world ain't going under (yet).

**Comment by LeeBinder** [comment]
@androidacy-user Can you please also update the apks on the [GitHub 2.1.1 release page](https://github.com/Androidacy/MagiskModuleManager/releases/tag/v2.1.1) with the fixed (and signed) ones from the [Androidacy Downloads Center page](https://www.androidacy.com/downloads/?view=FoxMMM)? I only tested the universal apk from GitHub but it's still the old faulty expired one and flakes out..

Thank you.

**Comment by chakflying** [comment]
Re-releasing with the same version code is a pretty poor decision. It's not even like nothing has changed, looking at the latest commit quite a lot of refactoring happened. Now we have a completely broken 2.1.1 and a working fine 2.1.1, with no trivial way to distinguish between them.
