### ISSUE TITLE
[BUG] Suddenly app crashes constantly when opening

### ISSUE THREAD

**Issue by Bodenseematze** [Androidacy/MagiskModuleManager#34]
I  had the message that a module update is available - when I now start the FoxMMM it directly crashes.
I tried to "reset the app" - which leads to a German dialog (as my phone's language is German) with only possibility to do a "reset app" again - which does not help...

**Device info:**
 - Device: Samsung Galaxy S20FE (Exynos) - SM-G780F/DS
 - OS: Rooted Standard Samsung image SAOMC_SM-G780F_OXM_DBT_RR_0006DBT/DBT,DBT/EUX/DBT
          (Android 11, OneUI 3.1, Kernel 4.19.87-20970822)
 - App Version [e.g. 2.1.1]

**Additional context**

`Stacktrace: 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.MainActivity}: io.realm.exceptions.RealmFileException: Failed to open Realm file at path '/data/user/0/com.fox2code.mmm/realms/ReposList.realm': Realm file decryption failed (Decryption failed: 'unable to decrypt after 0 seconds (retry_count=4
      from=i != bytes_read
      size=4096)') (/data/user/0/com.fox2code.mmm/realms/ReposList.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: ACCESS_ERROR.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: io.realm.exceptions.RealmFileException: Failed to open Realm file at path '/data/user/0/com.fox2code.mmm/realms/ReposList.realm': Realm file decryption failed (Decryption failed: 'unable to decrypt after 0 seconds (retry_count=4
      from=i != bytes_read
      size=4096)') (/data/user/0/com.fox2code.mmm/realms/ReposList.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: ACCESS_ERROR.
	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
	at io.realm.internal.OsSharedRealm.<init>(SourceFile:11)
	at io.realm.internal.OsSharedRealm.getInstance(SourceFile:6)
	at hg.<init>(SourceFile:18)
	at lf1.<init>(SourceFile:8)
	at vf1.b(SourceFile:96)
	at lf1.l0(SourceFile:5)
	at com.fox2code.mmm.MainActivity.onCreate(SourceFile:77)
	at android.app.Activity.performCreate(Activity.java:8198)
	at android.app.Activity.performCreate(Activity.java:8182)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
	... 11 more
`

**Comment by zgfg** [comment]
What is 'comleted'- give me a link for the fixed version

Why are you lying - it's still the same v2.1.1 on GitHub, I have uninstalled, installed again it again crashes
