### ISSUE TITLE
[BUG] We hit a snag!

### ISSUE THREAD

**Issue by bphd** [Androidacy/MagiskModuleManager#36]
**Describe the bug**
Open

**To Reproduce**
5. open

**Expected behavior**
Main apm

**Screenshots**

**Device info(please complete the following information):**
 - OS: [ROM and version, ie Havoc-OS 4.12]
 - App Version [e.g. 22]

**Additional context**
Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.MainActivity}: io.realm.exceptions.RealmFileException: Failed to open Realm file at path '/data/user/0/com.fox2code.mmm/realms/ReposList.realm': Realm file decryption failed (Decryption failed: 'unable to decrypt after 0 seconds (retry_count=4
      from=i != bytes_read
      size=4096)') (/data/user/0/com.fox2code.mmm/realms/ReposList.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: ACCESS_ERROR.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4166)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4312)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: io.realm.exceptions.RealmFileException: Failed to open Realm file at path '/data/user/0/com.fox2code.mmm/realms/ReposList.realm': Realm file decryption failed (Decryption failed: 'unable to decrypt after 0 seconds (retry_count=4
      from=i != bytes_read
      size=4096)') (/data/user/0/com.fox2code.mmm/realms/ReposList.realm) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: ACCESS_ERROR.
	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
	at io.realm.internal.OsSharedRealm.<init>(SourceFile:11)
	at io.realm.internal.OsSharedRealm.getInstance(SourceFile:6)
	at hg.<init>(SourceFile:18)
	at lf1.<init>(SourceFile:8)
	at vf1.b(SourceFile:96)
	at lf1.l0(SourceFile:5)
	at com.fox2code.mmm.MainActivity.onCreate(SourceFile:77)
	at android.app.Activity.performCreate(Activity.java:8578)
	at android.app.Activity.performCreate(Activity.java:8557)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4147)
	... 12 more

**Comment by bphd** [comment]
You have to install signed (CRC32: 03957E94), not release (CRC32: 2E82BDD7). I've heard about problem about data/cache/app traces, so maybe deep clean or even a full uninstall if it doesn't work solely with update
