### ISSUE TITLE
[BUG] Instant crash on startup

### ISSUE THREAD

**Issue by downtoground** [Androidacy/MagiskModuleManager#37]
Stacktrace: 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.MainActivity}: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3641)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at com.fox2code.mmm.MainActivity.onCreate(SourceFile:791)
	at android.app.Activity.performCreate(Activity.java:8341)
	at android.app.Activity.performCreate(Activity.java:8320)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
	... 12 more

I'm on LOS20 + Microg.
Zygisk is on. The crash came out of nothing. Reset or erasing cache isn't going to help. 
Tried to reinstall without success. 

Seems there's nothing left I could do.

To be honest. The app feels extremely buggy after the migration. And became even worse with every new update. Really don't know what to expect. Sorry..

**Comment by zgfg** [comment]
What is 'comleted'- give me a link for the fixed version

Why are you lying - it's still the same v2.1.1 on GitHub, I have uninstalled, installed again it again crashes
