### ISSUE TITLE
[BUG] Crash after install

### ISSUE THREAD

**Issue by stenso** [Androidacy/MagiskModuleManager#40]
**Describe the bug**
After downloading and installing the arm64 version on my OnePlus8T running Lineage 20 (Android 13)

**To Reproduce**
1. Download arm64 APK from releases
2. Install app
3. Click open dialogue

**Expected behavior**
Normal behavior

**Device info(please complete the following information):**
 - Device: OnePlus8T
 - OS: Lineage OS 20
 - App Version 2.1.1

**Additional context**
Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.MainActivity}: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3641)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at com.fox2code.mmm.MainActivity.onCreate(SourceFile:791)
	at android.app.Activity.performCreate(Activity.java:8341)
	at android.app.Activity.performCreate(Activity.java:8320)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
	... 12 more

**Comment by cauzinnn** [comment]
same problem here. OnePlus 7 pro, also on Lineage 20
