### ISSUE TITLE
[BUG] Error when opening the app

### ISSUE THREAD

**Issue by BLACK4585** [Androidacy/MagiskModuleManager#41]
**Describe the bug**
I can't use the app because when I open it, it shows an Error Screen with an error code. Already tried to reset it, clear the cache and all data but this didn't work.

**To Reproduce**
1. Start the app
2. See error

**Expected behavior**
That the app starts.

**Screenshots**
GitHub app Crashes when I try to add a pic lol

**Device info(please complete the following information):**
 - Device: [Redmi Note 8 Pro]
 - OS: [CrDroid (Extended) 9.5 by Tim Josten]
 - App Version [2.1.1]

**Additional context**
`Stacktrace: 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.MainActivity}: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3651)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3788)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7896)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
Caused by: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
	at com.fox2code.mmm.MainActivity.onCreate(SourceFile:791)
	at android.app.Activity.performCreate(Activity.java:8359)
	at android.app.Activity.performCreate(Activity.java:8338)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3632)
	... 12 more
`

**Comment by maxsky** [comment]
Same error from XiaoMi 12 with MIUI 14 Global (Android 13)

**Comment by joeryru** [comment]
![Screenshot_20230618-053139_Fox's Magisk Module Manager](https://github.com/Androidacy/MagiskModuleManager/assets/5329034/a000b4ff-e0e5-4046-b0c8-b73a7b982941)
