### ISSUE TITLE
[BUG] REPLACE_ME

### ISSUE THREAD

**Issue by Dimon-015** [Androidacy/MagiskModuleManager#57]
**Describe the bug**
use as webview service, google chrome.
**To Reproduce**
1. Go to install via developer mode, google chrome for webview. 
2. Click on Then when you open the application, immediately crash. 
FATAL EXCEPTION: main
Process: com.fox2code.mmm, PID: 12942
java.lang.ExceptionInInitializerError
	at com.fox2code.mmm.MainApplication.c(SourceFile:55)
	at com.fox2code.mmm.MainApplication.onCreate(SourceFile:1038)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1283)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6790)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2130)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7925)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.ClassCastException: com.fox2code.mmm.MainApplication cannot be cast to kb0
	at ik0.<clinit>(SourceFile:60)
	... 13 more
![Screenshot_20230722-164002_Настройки](https://github.com/Androidacy/MagiskModuleManager/assets/114181146/777fe05c-7fc6-4ab7-ac41-17d2eee09c7d)

**Expected behavior**

**Screenshots**

**Device info(please complete the following information):**
 - Device: xiaomi mi 10 t pro
 - OS: Pixel Experience plus Android 13 
 - App Version 2.2.3 (81)

**Additional context**

**Comment by Dimon-015** [comment]
Thank you for the response. I have checked it. If I install Android System WebView, everything works fine. But if I choose Chrome WebView, it doesn't work.

**Comment by Dimon-015** [comment]
https://photos.app.goo.gl/V3B8EVA3SgNK5nvR6

**Comment by Dimon-015** [comment]
===============
[Device Brand]: Xiaomi
[Device Model]: M2007J3SY
[Display]: TQ2A.230505.002
[Android Version]: 13
[Android API Level]: 33
[System Locale]: ru_RU
[Process ID]: 25689
[CPU ABI]: arm64-v8a
[Package Name]: com.fox2code.mmm
[Version Name]: 2.3.3
[Version Code]: 4087
[Error Type]: JVM
[Crash Time]: 2023-09-21T02:18:07.062
[Stack Trace]:
java.lang.ExceptionInInitializerError
 at java.lang.Class.newInstance(Native Method)
 at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
 at androidx.core.app.CoreComponentFactory.instantiateApplication(Unknown Source:0)
 at android.app.Instrumentation.newApplication(Instrumentation.java:1245)
 at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
 at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6751)
 at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2130)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7925)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.IllegalStateException: Failed to get shared preferences
 at bm0.f(Unknown Source:125)
 at com.fox2code.mmm.MainApplication.<clinit>(Unknown Source:2)
 ... 16 more

**Comment by Dimon-015** [comment]
> > ===============
> > [Device Brand]: Xiaomi
> > [Device Model]: M2007J3SY
> > [Display]: TQ2A.230505.002
> > [Android Version]: 13
> > [Android API Level]: 33
> > [System Locale]: ru_RU
> > [Process ID]: 25689
> > [CPU ABI]: arm64-v8a
> > [Package Name]: com.fox2code.mmm
> > [Version Name]: 2.3.3
> > [Version Code]: 4087
> > [Error Type]: JVM
> > [Crash Time]: 2023-09-21T02:18:07.062
> > [Stack Trace]:
> > java.lang.ExceptionInInitializerError
> > at java.lang.Class.newInstance(Native Method)
> > at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
> > at androidx.core.app.CoreComponentFactory.instantiateApplication(Unknown Source:0)
> > at android.app.Instrumentation.newApplication(Instrumentation.java:1245)
> > at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
> > at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
> > at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6751)
> > at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2130)
> > at android.os.Handler.dispatchMessage(Handler.java:106)
> > at android.os.Looper.loopOnce(Looper.java:201)
> > at android.os.Looper.loop(Looper.java:288)
> > at android.app.ActivityThread.main(ActivityThread.java:7925)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
> > Caused by: java.lang.IllegalStateException: Failed to get shared preferences
> > at bm0.f(Unknown Source:125)
> > at com.fox2code.mmm.MainApplication.(Unknown Source:2)
> > ... 16 more
> 
> This is the result of intended behavior. You'll have to reset the app.
> 
> We changed behavior to remove the unencrypted preference fallback. If you continue to have issues after resetting, your ROM ships with a broken keystore implementation.

What should I do then? I even completely reinstalled the application. I am using Pixel Experience Plus firmware.

Even on another phone with stock firmware, it still doesn't work.

OnePlus 11 - Salami; PHB110 Android 13

FATAL EXCEPTION: main
Process: com.fox2code.mmm, PID: 23546
java.lang.ExceptionInInitializerError
 at java.lang.Class.newInstance(Native Method)
 at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
 at androidx.core.app.CoreComponentFactory.instantiateApplication(Unknown Source:0)
 at android.app.Instrumentation.newApplication(Instrumentation.java:1251)
 at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1503)
 at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1439)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7212)
 at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:240)
 at android.os.Looper.loop(Looper.java:351)
 at android.app.ActivityThread.main(ActivityThread.java:8422)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.IllegalStateException: Failed to get shared preferences
 at bm0.f(Unknown Source:125)
 at com.fox2code.mmm.MainApplication.<clinit>(Unknown Source:2)
 ... 16 more

**Comment by Dimon-015** [comment]
> > > > ===============
> > > > [Device Brand]: Xiaomi
> > > > [Device Model]: M2007J3SY
> > > > [Display]: TQ2A.230505.002
> > > > [Android Version]: 13
> > > > [Android API Level]: 33
> > > > [System Locale]: ru_RU
> > > > [Process ID]: 25689
> > > > [CPU ABI]: arm64-v8a
> > > > [Package Name]: com.fox2code.mmm
> > > > [Version Name]: 2.3.3
> > > > [Version Code]: 4087
> > > > [Error Type]: JVM
> > > > [Crash Time]: 2023-09-21T02:18:07.062
> > > > [Stack Trace]:
> > > > java.lang.ExceptionInInitializerError
> > > > at java.lang.Class.newInstance(Native Method)
> > > > at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
> > > > at androidx.core.app.CoreComponentFactory.instantiateApplication(Unknown Source:0)
> > > > at android.app.Instrumentation.newApplication(Instrumentation.java:1245)
> > > > at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
> > > > at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
> > > > at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6751)
> > > > at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
> > > > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2130)
> > > > at android.os.Handler.dispatchMessage(Handler.java:106)
> > > > at android.os.Looper.loopOnce(Looper.java:201)
> > > > at android.os.Looper.loop(Looper.java:288)
> > > > at android.app.ActivityThread.main(ActivityThread.java:7925)
> > > > at java.lang.reflect.Method.invoke(Native Method)
> > > > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> > > > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
> > > > Caused by: java.lang.IllegalStateException: Failed to get shared preferences
> > > > at bm0.f(Unknown Source:125)
> > > > at com.fox2code.mmm.MainApplication.(Unknown Source:2)
> > > > ... 16 more
> > > 
> > > 
> > > This is the result of intended behavior. You'll have to reset the app.
> > > We changed behavior to remove the unencrypted preference fallback. If you continue to have issues after resetting, your ROM ships with a broken keystore implementation.
> > 
> > 
> > What should I do then? I even completely reinstalled the application. I am using Pixel Experience Plus firmware.
> > Even on another phone with stock firmware, it still doesn't work.
> > OnePlus 11 - Salami; PHB110 Android 13
> > FATAL EXCEPTION: main
> > Process: com.fox2code.mmm, PID: 23546
> > java.lang.ExceptionInInitializerError
> > at java.lang.Class.newInstance(Native Method)
> > at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
> > at androidx.core.app.CoreComponentFactory.instantiateApplication(Unknown Source:0)
> > at android.app.Instrumentation.newApplication(Instrumentation.java:1251)
> > at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1503)
> > at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1439)
> > at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7212)
> > at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
> > at android.os.Handler.dispatchMessage(Handler.java:106)
> > at android.os.Looper.loopOnce(Looper.java:240)
> > at android.os.Looper.loop(Looper.java:351)
> > at android.app.ActivityThread.main(ActivityThread.java:8422)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
> > Caused by: java.lang.IllegalStateException: Failed to get shared preferences
> > at bm0.f(Unknown Source:125)
> > at com.fox2code.mmm.MainApplication.(Unknown Source:2)
> > ... 16 more
> 
> Please redownload the update manually. There's a chance you got the early bad update, but we pulled that within three hours of release.

Стек трассировки: 
java.lang.ExceptionInInitializerError
	at ok1.k(Unknown Source:0)
	at r91.b(Unknown Source:9)
	at z91.a(Unknown Source:5)
	at vw0.a(Unknown Source:6)
	at vw0.b(Unknown Source:100)
	at xm0.run(Unknown Source:71)
Caused by: java.lang.ClassCastException: com.fox2code.mmm.MainApplication cannot be cast to wa
	at hj0.<clinit>(Unknown Source:64)
	... 6 more

**Comment by JasonKhew96** [comment]
https://github.com/neoblackxt/AnyWebView/issues/12

**Comment by Dimon-015** [comment]
> > [neoblackxt/AnyWebView#12](https://github.com/neoblackxt/AnyWebView/issues/12)
> 
> Well THAT would have been useful information.
> 
> @Dimon-015 unfortunately, we cannot provide support if you're modifying the app or modifying system behavior the app relies on. Chrome is not supported on modern android for WebView and you'll have to select something else to use AMM.

Thank you for your response. But I initially told you that I am using Chrome webview. Well, as sad as it is, I will have to switch to MRepo. Just to clarify, this is not an advertisement, it's a statement of fact. Unfortunately.

**Comment by Dimon-015** [comment]
> > > > [neoblackxt/AnyWebView#12](https://github.com/neoblackxt/AnyWebView/issues/12)
> > > 
> > > 
> > > Well THAT would have been useful information.
> > > @Dimon-015 unfortunately, we cannot provide support if you're modifying the app or modifying system behavior the app relies on. Chrome is not supported on modern android for WebView and you'll have to select something else to use AMM.
> > 
> > 
> > Thank you for your response. But I initially told you that I am using Chrome webview. Well, as sad as it is, I will have to switch to MRepo. Just to clarify, this is not an advertisement, it's a statement of fact. Unfortunately.
> 
> I was unaware you were on an android version that didn't support this, and using a mod to change that behavior.
> 
> You really, really need to read. **Any app using actual WebView will crash** not just ours.

Just for your information, I have two applications that developers added support for Chrome's webview upon my request. So it is possible. However, if you choose not to do so, it is entirely your decision. I just provided this information for general knowledge.
