### ISSUE TITLE
[BUG] Module's name can be shown in different font size

### ISSUE THREAD

**Issue by giving-sesame** [Androidacy/MagiskModuleManager#6]
**Describe the bug**
When I launch MMM, some modules' names are shown in smaller font size. When I exit and then launch MMM again, those modules are shown in normal font size, but now other modules' names are smaller. This picture changes each time I launch the application.

**To Reproduce**
Just launch the application and check the list of modules. Some of them have names in smaller size.

**Expected behavior**
All modules' names are of the same size.

**Screenshots**
I added a gif explaining the problem. It contains 2 screenshots of 2 different launchs of MMM.
![235252744-55e6a686-445b-4e55-9604-71170e88f8e1](https://user-images.githubusercontent.com/76995969/236166166-caaca207-bf6c-4ba3-ad4b-222a78aa24b2.gif)

**Device info(please complete the following information):**
 - Device: Redmi 9
 - OS: crDroid 7.26, Android 11
 - 2.0.2 (in 2.0.1 this bug exists as well)

**Comment by giving-sesame** [comment]
> any difference with the latest actions build?

I installed this build. It has a different behaviour. At first, when the application is launched, some names are in smaller font size. Then after few seconds some refreshing of module list happens and those modules become to be in normal font size, but some other become to be in smaller font size.

Please look at the screen capture video. "APTX for Android Oreo & Pie" looks normal, "Cloudflare DNS" looks smaller. Then refreshing happens and "APTX" looks smaller, "Cloudflare" looks normal: [download video](https://app.box.com/s/x2hyqr436k77doh54x0vm5z6ws5rpwv3)

**Comment by giving-sesame** [comment]
> any difference with the latest actions build?

I installed this build. It has a different behaviour. At first, when the application is launched, some names are in smaller font size. Then after few seconds some refreshing of module list happens and those modules become to be in normal font size, but some other become to be in smaller font size.

BTW, in the version 2.1.1 behaviour is the same as in this debug build.

Please look at the screen capture video. "APTX for Android Oreo & Pie" looks normal, "Cloudflare DNS" looks smaller. Then refreshing happens and "APTX" looks smaller, "Cloudflare" looks normal: [download link](https://app.box.com/s/x2hyqr436k77doh54x0vm5z6ws5rpwv3)

**Comment by much-doge** [comment]
@androidacy-user even after downloading the latest build on the website (the signed version), the error still appear with the exact error

`Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.MainActivity}: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:237)
 at android.app.ActivityThread.main(ActivityThread.java:8167)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.IllegalStateException: This build has expired. Please download a stable build or update to the latest version.
 at com.fox2code.mmm.MainActivity.onCreate(SourceFile:791)
 at android.app.Activity.performCreate(Activity.java:7963)
 at android.app.Activity.performCreate(Activity.java:7952)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
 ... 11 more`

**Comment by Fox2Code** [comment]
I'll review this issues once my health is a bit better!
