### ISSUE TITLE
[BUG] Crashes upon startup

### ISSUE THREAD

**Issue by gaining** [Androidacy/MagiskModuleManager#77]
**Describe the bug**
Crashes as the app opens

**To Reproduce**
Tap app icon, windows opens with "Hit a snag" with error code:

Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void t21.g(java.lang.String
      java.util.HashMap)' on a null object reference
	at jw0.run(Unknown Source:582)
	at java.lang.Thread.run(Thread.java:919)

**Expected behavior**
Being able to use app after opening.

**Screenshots**
![Screenshot_20231001-183635](https://github.com/Androidacy/MagiskModuleManager/assets/7690230/ea6e4c06-8b81-4c74-9497-7b966dadc497)

**Device info(please complete the following information):**
 - Device: MotoG5
 - OS: Android 10
 - App Version: latest

**Additional context**

**Comment by marcdw1289** [comment]
Confirmed. With analytics off it crashes. After clearing data and starting over from the initial setup screen, toggling a repo also resulted in a crash. Had to make sure to enable analytics first before doing anything else.

**Comment by gaining** [comment]
> Do you have analytics disabled? We are aware of issues with analytics disabled, due to insufficient checks that are already fixed in the latest actions builds

Now that you mention this, I might've disabled analytics a few years ago. But most apps work without it

**Comment by MrNRod** [comment]
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void t21.g(java.lang.String
      java.util.HashMap)' on a null object reference
	at jw0.run(Unknown Source:582)
	at java.lang.Thread.run(Thread.java:1012)

Getting the same issue with Analytics disabled on 2.3.3 downloaded from fdroid
