### ISSUE TITLE
[BUG] crash after starting

### ISSUE THREAD

**Issue by CHoeb** [Androidacy/MagiskModuleManager#78]
- update to newest version 2.3.3-fdroid 
- update to newest magisk 26301 + patching & rebooting
- repeated crash after starting:
Backtrace: 
java.lang.NullPointerException: Attempt to read from field 'java.lang.Object t21.a' on a null object reference
	at jw0.run(Unknown Source:418)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

 - Device: FP4
 - OS: e_FP4-user 12 SQ3A.220705.004 eng.root.20230615.051601 dev-keys
 - App Version: latest

downgrade to 2.2.1 works fine

**Comment by scarlettekk** [comment]
Same here.
